os: osx
language: cpp
compiler: clang
branches:
    except: /^WIP-.*$/

install:
    - brew install glew glfw3 glm ninja
    - pip install --user buildfox
    - mv /Users/travis/Library/Python/2.7/bin/bf /usr/local/bin/

before_script:
    - make configure

script:
    - make test
