language: cpp

compiler:
    - clang

os:
    - osx

before_script:
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y libsfml-dev; fi
    - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install sfml cmake; fi

branches:
    only:
        - master

script: make && make test
