os: osx
language: cpp
compiler: clang
branches:
    only: master

install:
    - brew update
    - brew install glew glfw3 glm lcov
    - gem install coveralls-lcov

before_script:
    - export PATH=$PATH:/Library/Developer/CommandLineTools/usr/bin/

script:
    - make configure
    - make coverage

after_success:
    - coveralls-lcov coverage/cov.info
