language: cpp

compiler:
    - clang

before_install:
    - sudo apt-get update

before_script:
    - sudo apt-get install -y libsfml-dev

branches:
    only:
        - master

script: make && make test
