os: osx
language: cpp
compiler: clang
branches:
    only: master

install:
    - brew update
    - brew install glew
    - brew install glfw3
    - brew install glm

script:
    - make configure
    - make test
