language: cpp

compiler:
    - clang

before_install:
    - sudo apt-get update

before_script:
    - wget http://www.sfml-dev.org/files/SFML-2.2-linux-gcc-64-bit.tar.gz
    - tar -zxvf SFML-2.2-linux-gcc-64-bit.tar.gz --directory /tmp
    - sudo cp -r /tmp/SFML-2.2/* /usr/
    - sudo apt-get install -y libpthread-stubs0-dev libgl1-mesa-dev libxrandr-dev libfreetype6-dev libglew-dev libjpeg8-dev libsndfile1-dev libopenal-dev libudev-dev

branches:
    only:
        - master

script: make && make test
