language: cpp

compiler:
    - clang

before_install:
    - sudo apt-get update

before_script:
    - sudo apt-get install -y libsfml-dev
    - wget http://www.sfml-dev.org/files/SFML-2.2-linux-gcc-64-bit.tar.gz
    - tar -zxvf SFML-2.2-linux-gcc-64-bit.tar.gz --directory /tmp
    - sudo cp -r /tmp/SFML-2.2/* /usr/

branches:
    only:
        - master

script: make && make test
